
package hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

//Manually 
import java.awt.Image;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloIF", targetNamespace = "http://hello")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloIF {


    /**
     * 
     * @param s
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "image", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://hello", className = "hello.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://hello", className = "hello.SayHelloResponse")
    public Image sayHello(
        @WebParam(name = "s", targetNamespace = "")
        String s);

}
