
package hello;

import javax.jws.WebService;
import javax.xml.crypto.Data;
import javax.xml.ws.BindingType;

//Had to do this manually 
import javax.xml.ws.soap.MTOM;

import java.awt.Image;
import java.io.InputStream;
import java.io.IOException;
import javax.imageio.ImageIO;


//Test
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

import javax.activation.DataHandler;

import javax.imageio.ImageIO;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "HelloIF", serviceName = "HelloIF", targetNamespace = "http://hello", wsdlLocation = "WEB-INF/wsdl/HelloIF.wsdl", endpointInterface = "hello.HelloIF")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
//@MTOM
public class HelloIFImpl
    implements HelloIF
{


    public HelloIFImpl() {
    }

    /**
     * 
     * @param s
     * @return
     *     returns byte[]
     */
    public DataHandler sayHello(String s) {
        Image image = null;
        InputStream inputStream = null;
    	try {
    		System.out.println("Image path requested by client: " + s);
            //InputStream inputStream = getClass().getResourceAsStream(s);
            inputStream = getClass().getResourceAsStream(s);
    	    
    	    if(inputStream == null) {
    	    	
    	    	System.out.println("InputStream was null at path: " + s);
    	    	return null;
            }
            image = ImageIO.read(inputStream);

    	} catch (IOException ex) {
    	    ex.printStackTrace();
        }
        
        //return image;

        // BufferedImage temp = (BufferedImage) image;
        // ByteArrayOutputStream bos = new ByteArrayOutputStream();
        // try {
        //     ImageIO.write(temp, "png", bos );
        //     bos.close();
		// } catch (IOException e) {
		// 	e.printStackTrace();
        // }
        //return bos.toByteArray();
        DataHandler dataHandler = new DataHandler(new InputStreamDataSource(inputStream));
        return dataHandler;
    }

}
